export const fontFamily = {
	'roboto': [ 'Roboto', 'sans-serif' ],
	'noto-sans': [ 'NotoSans', 'sans-serif' ],
};

export const fontSize = {
	'x-small': '12px',
	'small': '14px',
	'default': '16px',
	'medium': '20px',
	'large': '22px',
	'x-large': '24px',
	'huge': '28px',
	'x-huge': '36px',
};

export const fontWeight = {
	'thin': '100',
	'extra-light': '200',
	'light': '300',
	'normal': '400',
	'medium': '500',
	'semi-bold': '600',
	'bold': '700',
	'extra-bold': '800',
	'heavy': '900',
	'ultra-black': '950',
};

export const colors = {
	'brand-main': '#074060',
	'brand-primary': '#A81D54',
	'brand-secondary': '#EBC163',
	'brand-tertiary': '#517E37',
	'basic-intense': '#FF5973',
	'basic-link': '#006BE2',
	'basic-light': '#D6F2FF',
	'basic-placeholder': '#888888',
	'feedback-info-light': '#D6F2FF',
	'feedback-info-default': '#006BE2',
	'feedback-info-dark': '#0D509B',
	'feedback-success-light': '#D6FFE6',
	'feedback-success-default': '#00A742',
	'feedback-success-dark': '#067532',
	'feedback-warning-light': '#FFF9C2',
	'feedback-warning-default': '#EFB003',
	'feedback-warning-dark': '#874B0C',
	'feedback-danger-light': '#FFDDE2',
	'feedback-danger-default': '#E20023',
	'feedback-danger-dark': '#AF051F',
	'stroke-light': '#E7E7E7',
	'stroke-default': '#D1D1D1',
	'stroke-dark': '#B0B0B0',
	'title-light': '#6D6D6D',
	'title-default': '#006CA7',
	'title-dark': '#262626',
	'paragraph-light': '#E7E7E7',
	'paragraph-default': '#4F4F4F 	',
	'paragraph-dark': '#262626',
	'background-light': '#FFFFFF',
	'background-default': '#FBFBFB',
	'background-dark': '#E7E7E7',
	'background-info': '#DFF2FF',
};

export const spacing = {
	'none': '0px',
	'base': '4px',
	'tiny': '8px',
	'small-x': '12px',
	'small-xx': '16px',
	'small-xxx': '20px',
	'normal-x': '24px',
	'normal-xx': '28px',
	'normal-xxx': '32px',
	'giant-x': '36px',
	'giant-xx': '40px',
	'giant-xxx': '48px',
	'huge-x': '52px',
	'huge-xx': '56px',
	'huge-xxx': '60px',
	'exepcional': '64px',
};

export const borderRadius = {
	'none': '0px',
	'base': '4px',
	'small': '8px',
	'default': '12px',
	'medium': '16px',
	'large': '24px',
	'circular': '1000px',
};
