export const API_ROUTES = {
	auth: {
		signIn: '/auth/sign_in',
		signUp: '/auth/sign_up',
		recoverPassword: '/auth/recover_password',
		resetPassword: '/auth/reset_password',
	},
	users: {
		me: '/users/me',
		updateMe: '/users/me',
	},
	wallets: {
		index: '/wallets',
		main: '/wallets/main',
		create: '/wallets',
		update: (id: string | number) => `/wallets/${ id }`,
		delete: (id: string | number) => `/wallets/${ id }`,
	},
	accounts: {
		index: '/accounts',
		create: '/accounts',
		show: (id: string | number) => `/accounts/${ id }`,
		update: (id: string | number) => `/accounts/${ id }`,
		delete: (id: string | number) => `/accounts/${ id }`,
	},
	creditBalances: {
		index: '/credit_balances',
		create: '/credit_balances',
		show: (id: string | number) => `/credit_balances/${ id }`,
		update: (id: string | number) => `/credit_balances/${ id }`,
		delete: (id: string | number) => `/credit_balances/${ id }`,
		invoice: (id: string | number) => `/credit_balances/${ id }/invoice`,
		payInvoice: (id: string | number) => `/credit_balances/${ id }/pay_invoice`,
	},
	creditCards: {
		index: '/credit_cards',
		create: '/credit_cards',
		show: (id: string | number) => `/credit_cards/${ id }`,
		update: (id: string | number) => `/credit_cards/${ id }`,
		delete: (id: string | number) => `/credit_cards/${ id }`,
	},
	transactions: {
		index: '/transactions',
		create: '/transactions',
		update: (id: string | number) => `/transactions/${ id }`,
		delete: (id: string | number) => `/transactions/${ id }`,
		settle: (id: string | number) => `/transactions/${ id }/settle`,
		unsettle: (id: string | number) => `/transactions/${ id }/unsettle`,
	},
	userWallets: {
		listInvites: '/user_wallets',
		createInvite: '/user_wallets',
		acceptInvite: (id: string | number) => `/user_wallets/${ id }/accept`,
		rejectInvite: (id: string | number) => `/user_wallets/${ id }/reject`,
	},
	core: {
		enumOptions: (entity: string, type: string) => `/core/enums/options/${ entity }/${ type }`,
		version: '/core/version',
	},
} as const;
